package com.redhat.atm.model;

public interface Constants {
    //Topic
    String ARRIVAL_ORDER_TOPIC = "ARRIVAL_ORDER_TOPIC";

    //Queues
    String ARRIVAL_SEQUENCE_DATA_A = "ARRIVAL_SEQUENCE_DATA_A";
    String ARRIVAL_SEQUENCE_DATA_B = "ARRIVAL_SEQUENCE_DATA_B";
    String ARRIVAL_SEQUENCE_DATA_C = "ARRIVAL_SEQUENCE_DATA_C";
    String ARRIVAL_SEQUENCE_DATA_D = "ARRIVAL_SEQUENCE_DATA_D";
    String ARRIVAL_SEQUENCE_DATA_E = "ARRIVAL_SEQUENCE_DATA_E";
}
