spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: k8s-secret-update
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace