apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-secret-update-roles
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - 'get'
      - 'update'
      - 'patch'
      - 'create'
      - 'list'
      - 'delete'