//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.24 at 12:42:06 AM CEST 
//


package com.redhat.atm.ed254;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:x-eurocae-example:service:aman:pub}flightID"/&gt;
 *         &lt;element ref="{urn:x-eurocae-example:service:aman:pub}point" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{urn:x-eurocae-example:service:aman:pub}atldt"/&gt;
 *         &lt;element ref="{urn:x-eurocae-example:service:aman:pub}assignedArrRwy"/&gt;
 *         &lt;element ref="{urn:x-eurocae-example:service:aman:pub}aircraft"/&gt;
 *         &lt;element ref="{urn:x-eurocae-example:service:aman:pub}handling"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "flightID",
    "point",
    "atldt",
    "assignedArrRwy",
    "aircraft",
    "handling"
})
@XmlRootElement(name = "entry")
public class Entry {

    @XmlElement(required = true)
    protected FlightID flightID;
    @XmlElement(required = true)
    protected List<Point> point;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar atldt;
    @XmlElement(required = true)
    protected AssignedArrRwy assignedArrRwy;
    @XmlElement(required = true)
    protected Aircraft aircraft;
    @XmlElement(required = true)
    protected Handling handling;

    /**
     * Gets the value of the flightID property.
     * 
     * @return
     *     possible object is
     *     {@link FlightID }
     *     
     */
    public FlightID getFlightID() {
        return flightID;
    }

    /**
     * Sets the value of the flightID property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightID }
     *     
     */
    public void setFlightID(FlightID value) {
        this.flightID = value;
    }

    /**
     * Gets the value of the point property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the point property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Point }
     * 
     * 
     */
    public List<Point> getPoint() {
        if (point == null) {
            point = new ArrayList<Point>();
        }
        return this.point;
    }

    /**
     * Gets the value of the atldt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAtldt() {
        return atldt;
    }

    /**
     * Sets the value of the atldt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAtldt(XMLGregorianCalendar value) {
        this.atldt = value;
    }

    /**
     * Gets the value of the assignedArrRwy property.
     * 
     * @return
     *     possible object is
     *     {@link AssignedArrRwy }
     *     
     */
    public AssignedArrRwy getAssignedArrRwy() {
        return assignedArrRwy;
    }

    /**
     * Sets the value of the assignedArrRwy property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssignedArrRwy }
     *     
     */
    public void setAssignedArrRwy(AssignedArrRwy value) {
        this.assignedArrRwy = value;
    }

    /**
     * Gets the value of the aircraft property.
     * 
     * @return
     *     possible object is
     *     {@link Aircraft }
     *     
     */
    public Aircraft getAircraft() {
        return aircraft;
    }

    /**
     * Sets the value of the aircraft property.
     * 
     * @param value
     *     allowed object is
     *     {@link Aircraft }
     *     
     */
    public void setAircraft(Aircraft value) {
        this.aircraft = value;
    }

    /**
     * Gets the value of the handling property.
     * 
     * @return
     *     possible object is
     *     {@link Handling }
     *     
     */
    public Handling getHandling() {
        return handling;
    }

    /**
     * Sets the value of the handling property.
     * 
     * @param value
     *     allowed object is
     *     {@link Handling }
     *     
     */
    public void setHandling(Handling value) {
        this.handling = value;
    }

}
