//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.24 at 12:42:06 AM CEST 
//


package com.redhat.atm.ed254;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PointUsageType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="PointUsageType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="IAF"/&gt;
 *     &lt;enumeration value="FAF"/&gt;
 *     &lt;enumeration value="STX"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PointUsageType")
@XmlEnum
public enum PointUsageType {

    IAF,
    FAF,
    STX;

    public String value() {
        return name();
    }

    public static PointUsageType fromValue(String v) {
        return valueOf(v);
    }

}
