//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.24 at 12:42:06 AM CEST 
//


package com.redhat.atm.model.ed254;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:x-eurocae-example:service:aman:pub}arctyp"/&gt;
 *         &lt;element ref="{urn:x-eurocae-example:service:aman:pub}wktrc"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "arctyp",
    "wktrc"
})
@XmlRootElement(name = "aircraft")
public class Aircraft {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String arctyp;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String wktrc;

    /**
     * Gets the value of the arctyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArctyp() {
        return arctyp;
    }

    /**
     * Sets the value of the arctyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArctyp(String value) {
        this.arctyp = value;
    }

    /**
     * Gets the value of the wktrc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWktrc() {
        return wktrc;
    }

    /**
     * Sets the value of the wktrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWktrc(String value) {
        this.wktrc = value;
    }

}
