//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.24 at 12:42:06 AM CEST 
//


package com.redhat.atm.model.ed254;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:x-eurocae-example:service:aman:pub}messageMeta"/&gt;
 *         &lt;element ref="{urn:x-eurocae-example:service:aman:pub}entry" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="topic" use="required" type="{urn:x-eurocae-example:service:aman:pub}TopicType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageMeta",
    "entry"
})
@XmlRootElement(name = "arrivalSequence")
public class ArrivalSequence {

    @XmlElement(required = true)
    protected MessageMeta messageMeta;
    @XmlElement(required = true)
    protected List<Entry> entry;
    @XmlAttribute(name = "topic", required = true)
    protected TopicType topic;

    /**
     * Gets the value of the messageMeta property.
     * 
     * @return
     *     possible object is
     *     {@link MessageMeta }
     *     
     */
    public MessageMeta getMessageMeta() {
        return messageMeta;
    }

    /**
     * Sets the value of the messageMeta property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageMeta }
     *     
     */
    public void setMessageMeta(MessageMeta value) {
        this.messageMeta = value;
    }

    /**
     * Gets the value of the entry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the entry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Entry }
     * 
     * 
     */
    public List<Entry> getEntry() {
        if (entry == null) {
            entry = new ArrayList<Entry>();
        }
        return this.entry;
    }

    /**
     * Gets the value of the topic property.
     * 
     * @return
     *     possible object is
     *     {@link TopicType }
     *     
     */
    public TopicType getTopic() {
        return topic;
    }

    /**
     * Sets the value of the topic property.
     * 
     * @param value
     *     allowed object is
     *     {@link TopicType }
     *     
     */
    public void setTopic(TopicType value) {
        this.topic = value;
    }

}
