//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.24 at 12:42:06 AM CEST 
//


package com.redhat.atm.model.ed254;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:x-eurocae-example:service:aman:pub}arcid"/&gt;
 *         &lt;element ref="{urn:x-eurocae-example:service:aman:pub}adep"/&gt;
 *         &lt;element ref="{urn:x-eurocae-example:service:aman:pub}ades"/&gt;
 *         &lt;element ref="{urn:x-eurocae-example:service:aman:pub}eobt"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "arcid",
    "adep",
    "ades",
    "eobt"
})
@XmlRootElement(name = "flightID")
public class FlightID {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String arcid;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String adep;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String ades;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eobt;

    /**
     * Gets the value of the arcid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArcid() {
        return arcid;
    }

    /**
     * Sets the value of the arcid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArcid(String value) {
        this.arcid = value;
    }

    /**
     * Gets the value of the adep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdep() {
        return adep;
    }

    /**
     * Sets the value of the adep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdep(String value) {
        this.adep = value;
    }

    /**
     * Gets the value of the ades property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdes() {
        return ades;
    }

    /**
     * Sets the value of the ades property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdes(String value) {
        this.ades = value;
    }

    /**
     * Gets the value of the eobt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEobt() {
        return eobt;
    }

    /**
     * Sets the value of the eobt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEobt(XMLGregorianCalendar value) {
        this.eobt = value;
    }

}
