//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.24 at 12:42:06 AM CEST 
//


package com.redhat.atm.model.ed254;

import java.math.BigInteger;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.redhat.atm.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Arcid_QNAME = new QName("urn:x-eurocae-example:service:aman:pub", "arcid");
    private final static QName _Adep_QNAME = new QName("urn:x-eurocae-example:service:aman:pub", "adep");
    private final static QName _Ades_QNAME = new QName("urn:x-eurocae-example:service:aman:pub", "ades");
    private final static QName _Eobt_QNAME = new QName("urn:x-eurocae-example:service:aman:pub", "eobt");
    private final static QName _Aptto_QNAME = new QName("urn:x-eurocae-example:service:aman:pub", "aptto");
    private final static QName _Pfl_QNAME = new QName("urn:x-eurocae-example:service:aman:pub", "pfl");
    private final static QName _Ttl_QNAME = new QName("urn:x-eurocae-example:service:aman:pub", "ttl");
    private final static QName _Atldt_QNAME = new QName("urn:x-eurocae-example:service:aman:pub", "atldt");
    private final static QName _Arctyp_QNAME = new QName("urn:x-eurocae-example:service:aman:pub", "arctyp");
    private final static QName _Wktrc_QNAME = new QName("urn:x-eurocae-example:service:aman:pub", "wktrc");
    private final static QName _Seqnr_QNAME = new QName("urn:x-eurocae-example:service:aman:pub", "seqnr");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.redhat.atm.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArrivalSequence }
     * 
     */
    public ArrivalSequence createArrivalSequence() {
        return new ArrivalSequence();
    }

    /**
     * Create an instance of {@link MessageMeta }
     * 
     */
    public MessageMeta createMessageMeta() {
        return new MessageMeta();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link FlightID }
     * 
     */
    public FlightID createFlightID() {
        return new FlightID();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link AssignedArrRwy }
     * 
     */
    public AssignedArrRwy createAssignedArrRwy() {
        return new AssignedArrRwy();
    }

    /**
     * Create an instance of {@link Aircraft }
     * 
     */
    public Aircraft createAircraft() {
        return new Aircraft();
    }

    /**
     * Create an instance of {@link Handling }
     * 
     */
    public Handling createHandling() {
        return new Handling();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:x-eurocae-example:service:aman:pub", name = "arcid")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createArcid(String value) {
        return new JAXBElement<String>(_Arcid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:x-eurocae-example:service:aman:pub", name = "adep")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAdep(String value) {
        return new JAXBElement<String>(_Adep_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:x-eurocae-example:service:aman:pub", name = "ades")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAdes(String value) {
        return new JAXBElement<String>(_Ades_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "urn:x-eurocae-example:service:aman:pub", name = "eobt")
    public JAXBElement<XMLGregorianCalendar> createEobt(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Eobt_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "urn:x-eurocae-example:service:aman:pub", name = "aptto")
    public JAXBElement<XMLGregorianCalendar> createAptto(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Aptto_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:x-eurocae-example:service:aman:pub", name = "pfl")
    public JAXBElement<String> createPfl(String value) {
        return new JAXBElement<String>(_Pfl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "urn:x-eurocae-example:service:aman:pub", name = "ttl")
    public JAXBElement<BigInteger> createTtl(BigInteger value) {
        return new JAXBElement<BigInteger>(_Ttl_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "urn:x-eurocae-example:service:aman:pub", name = "atldt")
    public JAXBElement<XMLGregorianCalendar> createAtldt(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Atldt_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:x-eurocae-example:service:aman:pub", name = "arctyp")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createArctyp(String value) {
        return new JAXBElement<String>(_Arctyp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:x-eurocae-example:service:aman:pub", name = "wktrc")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createWktrc(String value) {
        return new JAXBElement<String>(_Wktrc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "urn:x-eurocae-example:service:aman:pub", name = "seqnr")
    public JAXBElement<BigInteger> createSeqnr(BigInteger value) {
        return new JAXBElement<BigInteger>(_Seqnr_QNAME, BigInteger.class, null, value);
    }

}
