//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.24 at 12:42:06 AM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:x-eurocae-example:service:aman:pub", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.redhat.atm.model.ed254;
