//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.24 at 12:42:06 AM CEST 
//


package com.redhat.atm.model.ed254;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TopicType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TopicType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="ARRIVAL_SEQUENCE_DATA_A"/&gt;
 *     &lt;enumeration value="ARRIVAL_SEQUENCE_DATA_B"/&gt;
 *     &lt;enumeration value="ARRIVAL_SEQUENCE_DATA_C"/&gt;
 *     &lt;enumeration value="ARRIVAL_SEQUENCE_DATA_D"/&gt;
 *     &lt;enumeration value="ARRIVAL_SEQUENCE_DATA_E"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TopicType")
@XmlEnum
public enum TopicType {

    ARRIVAL_SEQUENCE_DATA_A,
    ARRIVAL_SEQUENCE_DATA_B,
    ARRIVAL_SEQUENCE_DATA_C,
    ARRIVAL_SEQUENCE_DATA_D,
    ARRIVAL_SEQUENCE_DATA_E;

    public String value() {
        return name();
    }

    public static TopicType fromValue(String v) {
        return valueOf(v);
    }

}
