kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-rhbk
  namespace: nav-portugal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: postgresql-rhbk
  namespace: nav-portugal
spec:
  serviceName: postgresql-rhbk-service
  selector:
    matchLabels:
      app: postgresql-rhbk
  template:
    metadata:
      labels:
        app: postgresql-rhbk
    spec:
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-rhbk
      containers:
        - name: postgresql-rhbk
          image: registry.redhat.io/rhel9/postgresql-16:latest
          resources:
            limits:
              memory: 512Mi
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: rhbk-db-secret
                  key: database-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rhbk-db-secret
                  key: database-password
            - name: POSTGRESQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rhbk-db-secret
                  key: database-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: rhbk-db-secret
                  key: database-name
          ports:
            - containerPort: 5432
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/pgsql/data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-rhbk
  namespace: nav-portugal
spec:
  selector:
    app: postgresql-rhbk
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432