apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: rhbk
  name: rhbk-keycloak
  namespace: nav-portugal
spec:
  features:
    enabled:
      - preview
  db:
    host: postgresql
    passwordSecret:
      key: database-password
      name: rhbk-db-secret
    url: 'jdbc:postgresql://postgres-rhbk.nav-portugal.svc.cluster.local:5432/keycloak'
    usernameSecret:
      key: database-user
      name: rhbk-db-secret
    vendor: postgres
  hostname:
    hostname: rhbk-nav-portugal.apps.ocp4.masales.cloud
    strict: false
    strictBackchannel: false
  http:
    tlsSecret: rhbk-tls-secret
    httpEnabled: true
  instances: 1
  transaction:
    xaEnabled: false
  additionalOptions:
    - name: proxy
      value: edge
    - name: hostname-debug
      value: 'true'
    - name: hostname-strict-https
      value: 'false'